/*
 * Room List API
 *
 * Hospital Room List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: pfx@google.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package premises_wl

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

type BuildingsAPI interface {

	// internal registration of api routes
	addRoutes(routerGroup *gin.RouterGroup)

	// CreateBuilding - Saves new building definition
	CreateBuilding(ctx *gin.Context)

	// DeleteBuilding - Deletes specific building
	DeleteBuilding(ctx *gin.Context)
}

// partial implementation of BuildingsAPI - all functions must be implemented in add on files
type implBuildingsAPI struct {
}

func newBuildingsAPI() BuildingsAPI {
	return &implBuildingsAPI{}
}

func (this *implBuildingsAPI) addRoutes(routerGroup *gin.RouterGroup) {
	routerGroup.Handle(http.MethodPost, "/building", this.CreateBuilding)
	routerGroup.Handle(http.MethodDelete, "/building/:buildingId", this.DeleteBuilding)

}

// Copy following section to separate file, uncomment, and implemented as needed
// // CreateBuilding - Saves new building definition
// func (this *implBuildingsAPI) CreateBuilding(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
// // DeleteBuilding - Deletes specific building
// func (this *implBuildingsAPI) DeleteBuilding(ctx *gin.Context) {
//  	ctx.AbortWithStatus(http.StatusNotImplemented)
// }
//
