/*
 * Room List API
 *
 * Hospital Room List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: pfx@google.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package premises_wl

type RoomEntry struct {

	// Unique id of the room in this list
	Id string `json:"id"`

	// Type of the room (e.g., ICU, surgery, general)
	Type string `json:"type"`

	// Current occupancy status (e.g., Occupied, Available)
	Status string `json:"status"`

	// Number of beds in the room
	Capacity int32 `json:"capacity"`
}
