/*
 * Room List API
 *
 * Hospital Room List management for Web-In-Cloud system
 *
 * API version: 1.0.0
 * Contact: pfx@google.com
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package premises_wl

import (
    "github.com/gin-gonic/gin"
)

func AddRoutes(engine *gin.Engine) {
  group := engine.Group("/api")
  
  {
    api := newBuildingsAPI()
    api.addRoutes(group)
  }
  
  {
    api := newRoomsListAPI()
    api.addRoutes(group)
  }
  
}