kind: Service
apiVersion: v1
metadata:
  name: vecnehladny-premises-webapi
spec:
  selector:
    pod: vecnehladny-premises-webapi-label
  ports:
  - name: http
    protocol: TCP
    port: 80
    targetPort: webapi-port